# Generated by Django 3.2.5 on 2022-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_padrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='media/profile/placeholder.png', null=True, upload_to='profile/'),
        ),
    ]
