# Generated by Django 3.2.5 on 2022-07-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220702_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='padrequest',
            name='donated',
            field=models.IntegerField(default=0),
        ),
    ]
