# Generated by Django 3.2.5 on 2022-07-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20220702_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrequest',
            name='image',
            field=models.CharField(blank=True, default='https://complianz.io/wp-content/uploads/2019/03/placeholder-300x202.jpg', max_length=90),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profile/placeholder.png', null=True, upload_to='profile/'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_created=True, auto_now=True)),
                ('amount', models.IntegerField(default=1)),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.padrequest')),
            ],
        ),
    ]
